export const ENV_VAR_NAMES = {
  NODE_ENV: 'NODE_ENV',

  // server
  API_PORT: 'API_PORT',
  SERVER_PREFIX: 'SERVER_PREFIX',
  GLOBAL_PREFIX: 'GLOBAL_PREFIX',

  // db
  DATABASE_URL: 'DATABASE_URL',

  // logging
  ENABLE_FILE_LOGGER: 'ENABLE_FILE_LOGGER',

  // s3
  AWS_BUCKET_NAME: 'AWS_BUCKET_NAME',
  AWS_BUCKET_REGION: 'AWS_BUCKET_REGION',
  S3_ACCESS_KEY_ID: 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY: 'S3_SECRET_ACCESS_KEY',

  // DynamoDB
  DYNAMODB_REGION: 'DYNAMODB_REGION',
  DYNAMODB_ACCESS_KEY_ID: 'DYNAMODB_ACCESS_KEY_ID',
  DYNAMODB_SECRET_ACCESS_KEY: 'DYNAMODB_SECRET_ACCESS_KEY',
};

export enum NODE_ENV_ENUM {
  DEV = 'dev',
  TEST = 'test',
  STAGING = 'staging',
  PROD = 'prod',
}
