version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine3.16
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
